### PR TITLE
Add space to match on dir create

### PR DESCRIPTION
**Pull request by lil5**
- [ ] Path in title will show "%20" instead of " " [possible changes](https://github.com/dom111/webdav-js/pull/24#issuecomment-442087354)
- [ ] No yet minified
- [ ] Downloads with `%20` instead of space
- [x] mkdir support

#19

### CODE REVIEW

**Comment by dom111** [comment]
This is an interesting problem!

I think supporting spaces in the directory name is good, but it looks like the same URL param decode routine needs to be added to directories to ensure they aren't broken. I think this might also uncover problems with UTF-8 encoded characters and Emoji... Will try and test this when I have time!

**Comment by nielll** [comment]
The same changes has to be done at the **line 120** when a folder or file is renamed

```javascript
  if (!to.match(/^[a-z0-9_\-\.]+$/i)) {
                        _message('Bad file name.');
                        to = false;
```

**Comment by lil5** [comment]
https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space

From what I'm reading is that it might be best to replace `%20` (aka _space_) with `_`
Any thoughts?

**Comment by dom111** [comment]
Interesting. Agree that spaces aren't usually needed, but there could be reasons for doing so. Perhaps it should warn and provide an alternative? Ensuring the spaces (and other UTF-8 encodings) are decoded properly should definitely be validated too.

**Comment by dom111** [comment]
So I've updated the file to support adding files and directories with spaces now, it appears to be working for me, but I've asked @nielll to take a look under #19. It does raise more questions though, like, should a wider range of characters be supported? There are only a few 'special' chars, would it be better to just handle those edge cases (spaces, slashes, etc) and blindly allow potentially invalid requests through after encoding with `encodeURIComponent`?

**Comment by dom111** [comment]
I'll close this PR, as the issues noted are resolved under #32, #33, #34 and #19 is open awaiting confirmation from @nielll.

**Pull request closed without merging**
