### PR TITLE
Non breaking space #35

### PR DESCRIPTION
**Pull request by lil5**

### CODE REVIEW

**Comment by lil5** [comment]
:warning: Is not yet minified!

**Comment by lil5** [comment]
@dom111 Any other texts you can think of that might improve with `&nbsp;`?

**Comment by dom111** [comment]
> @dom111 Any other texts you can think of that might improve with `&nbsp;`?

Not off-hand! This is a good amend, might be something that's better handled via CSS but this works well for now! I've been thinking about the English that's in place at the moment, and wondering about `i18n`/`l10n`, but I think if there's currently no call for it, there's no need to add for now. Perhaps this would be better replaced with an icon or something in a future iteration?

**Comment by lil5** [comment]
> > @dom111 Any other texts you can think of that might improve with `&nbsp;`?
> 
> Not off-hand! This is a good amend, might be something that's better handled via CSS but this works well for now! I've been thinking about the English that's in place at the moment, and wondering about `i18n`/`l10n`, but I think if there's currently no call for it, there's no need to add for now. Perhaps this would be better replaced with an icon or something in a future iteration?

`&nbsp;` is the proper way of defining which words stick together. Using spans for this would actually be bad form.

Placing the `New directory` button/link somewhere else would be the best in the end but requires #25 .2 to be complete.

**Comment by lil5** [comment]
https://github.com/dom111/webdav-js/pull/36/commits/9357a67b75bd700e819c6d16a4e21b7e49254565 done

please merge

**Pull request merged**
