### PR TITLE
Entire page dropzone and add mobile friendly upload control

### LINKED ISSUE #2: Make entire page a dropzone for drag and drop upload
Currently, only the deliberate dropzone at the bottom of the page can have files dropped on to it, but I think it'd be better to have a dropzone for the whole page.

Nice to have: when dropped onto a folder, upload to that folder.
Nice to have: when hovered over a folder for 2-3 seconds, load that folder. Include parent folder in this.
Nice to have: allow moving files using the same mechanism.
Nice to have: allow copying files using the same mechanism + Ctrl/Cmd

Possible bug: ensure cache is updated on file upload (thanks @dmitrydvorkin on #1)

### PR DESCRIPTION
**Pull request by dom111**
Initial commit for entire page dropzones and dragging over directories uploading there
Added in mobile friendly upload control
This fixes #2 and #25.2

@lil5 Would you be willing to take a look through this?

### CODE REVIEW

**Comment by lil5** [comment]
Testing.. There are errors will PR soon

**Comment by lil5** [comment]
Also this does fix #25.2

**Comment by dom111** [comment]
@lil5 The changes for the file input will only show up on a mobile device:

https://github.com/dom111/webdav-js/pull/42/commits/48a8b7d06c533a7f0a0cb2342142dd6eab53e2dc#diff-1ad7ecb784ab7e0c330ecb8c28e6c149R443

Thanks for taking a look, appreciate it!

**Comment by lil5** [comment]
> @lil5 The changes for the file input will only show up on a mobile device:
> 
> [48a8b7d#diff-1ad7ecb784ab7e0c330ecb8c28e6c149R443](https://github.com/dom111/webdav-js/commit/48a8b7d06c533a7f0a0cb2342142dd6eab53e2dc#diff-1ad7ecb784ab7e0c330ecb8c28e6c149R443)
> 
> Thanks for taking a look, appreciate it!

Very nice :+1:

**Comment by dom111** [comment]
I've fixed the .js files being parsed via `globalEval`, so I think this is good now! With your #44, do you think this is good to go?

**Pull request merged**
